project:
  type: website
  output-dir: docs

website:
  title: "Duke Admissions and Enrollment"
  reader-mode: true
  repo-url: https://github.com/lisapzhang/idhfinal
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    left:
    - index.qmd
    - gender.qmd
    - department.qmd
    - geographical.qmd

format: 
  pdf: default
  html: 
    theme: sandstone
    mainfont: "Atkinson Hyperlegible"
    toc: true

editor: visual