---
title: "Department Distribution"
format: html
echo: false
editor: source
---



```{r}
#| message = FALSE
library(ggplot2)
library(tidyverse)
library(dplyr)
library(robotstxt)
library(rvest)
library(kableExtra)
```

```{r}
#| message = FALSE
census <- read_csv("~/idhfinal/data/census.csv")
```


```{r}
#| label: fig-departmentdistr
#| fig-cap: "The number of students in each department from spring 1933 to spring 1943"
#| fig-width: 10
#| fig-height: 10
census |>
  drop_na() |>
  filter(Department != "Engineering",
         Department != "Civil Engineering",
         Department != "Mechanical Engineering") |> 
  ggplot(
    aes(x = Year, y = `Number Students`, color = Semester)) +
  geom_point() +
  facet_wrap(~Department,
             labeller = labeller(Department = label_wrap_gen(width = 25))) +
  labs(title = "Department Distribution Over the Years") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1)) +
  scale_x_continuous(n.breaks = 10)
```

```{r}
#| message = FALSE
censuscurrent <- read_csv("~/idhfinal/data/currentcensus.csv")
```

```{r}
#| message = FALSE
censuscurrent <- censuscurrent |>
  slice(1:57) |>
  select(1:2)
```

```{r}
#| label: tbl-majorsnow
#| tbl-cap: "The breakdown of graduates by major, 2021"
censuscurrent |>
  kbl(col.names = c("Major", "Percent")) |>
    kable_paper("hover", "striped")
```

