---
title: "Sources"
format: html
editor: source
---

Data from:

Duke University Archives

Office of the University Registrar records, 1853-2000

Statistics, 1925-1999

-   Box 30: Statistics, 1925-1948

-   Box 31: Statistics, 1948-1969

-   Box 32: Statistics, 1969-1999

-   Box 36: Class Census Reports (6 folders), 1932-1943

Other Works Cited:

Bureau, US Census. "Cartographic Boundary Files - Shapefile." Census.gov, 8 Oct. 2021, census.gov.

"Duke in Pictures: Duke's Wartime History." Duke Today, today.duke.edu.

"Duke University Graduation Rate & Retention Rate." College Factual, College Factual, 30 Mar. 2023, collegefactual.com.

Kasia. "Duke Chapel - Duke University Chapel Sketch , Free Transparent Clipart - ClipartKey." Clipartkey.com, clipartkey.com.

Rimer, Sara. "Social Expectations Pressuring Women at Duke, Study Finds." *The New York Times*, The New York Times, 24 Sept. 2003, nytimes.com.

"Servicemen's Readjustment Act (1944)." National Archives and Records Administration, National Archives and Records Administration, archives.gov.

"The Duke Freshman Record, Class of 1976." HathiTrust, babel.hathitrust.org.

Tierney, William G. "Higher Ed Should Learn Lessons from World War II about Serving the Public Good (Opinion)." Inside Higher Ed \| Higher Education News, Events and Jobs, insidehighered.com.

"Washington Duke and the Education of Women." Duke University Libraries, library.duke.edu.

"Woman's College Records, 1928-1974 - Archives & Manuscripts at Duke University Libraries." David M. Rubenstein Rare Book & Manuscript Library, archives.lib.duke.edu.
